root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

env_files = [".env"]

[build]
  cmd = "go build -o ./tmp/main ./cmd/sisima"
  bin = "tmp/main"

  delay = 1000

  include_ext = ["go"]
  include_dir = ["cmd", "internal"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false

  stop_on_error = true
  kill_delay = "0s"
  send_interrupt = true
  rerun = false
  rerun_delay = 500

  pre_cmd = []
  post_cmd = []

  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0
  app_start_timeout = 0
